PORT := 8080
IMAGE_TAG := hello-java-3m

.PHONY: help
help: ## show all targets help
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//''

.PHONY: build
build: ## build target that will perform a docker build command against our Dockerfile
	docker build -t ${IMAGE_TAG} .

build-compose: ## build target that will perform a docker build command against our Dockerfile
	docker-compose build

up-compose: ## build target that will perform a docker build command against our Dockerfile
	docker-compose up -d

.PHONY: run
run: ## run target that will perform a docker run command against our docker image
	docker run --cidfile cid.txt -p ${PORT}:${PORT} ${IMAGE_TAG}

.PHONY: clean
clean: ## cleanup target that runs shell script that removes files generated by the build and removes the image tag we built
	-docker stop `cat cid.txt`
	-docker rm `cat cid.txt`
	-docker rmi -f ${IMAGE_TAG}